---
name: Integration tests
# Impure, cross platform integration tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - host: ubuntu-24.04
          - host: windows-2019
          - host: macos-13 # x86_64
          - host: macos-14 # aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
        with:
          luarocksVersion: "3.11.0"
      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install rocks.nvim
        run: |
          mkdir rocks
          luarocks --tree ./rocks --lua-version=5.1 --server='https://nvim-neorocks.github.io/rocks-binaries/' make ./rocks.nvim-scm-1.rockspec
      - name: Remove system luarocks
        shell: bash
        if: startsWith(matrix.os.host, 'ubuntu') || startsWith(matrix.os.host, 'macos')
        run: rm -r .luarocks 
      - name: Run neovim with rocks.nvim
        shell: bash
        run: |
          ls rocks/lib/lua/5.1
          nvim -u .github/resources/init-integration.lua -l .github/resources/install-colorscheme.lua +q
          ls rocks
          # Will fail if rocks.log does not exist
          cat rocks/rocks.log
          echo "vim.cmd.colorscheme('sweetie')" >> .github/resources/init-integration.lua
          echo "vim.cmd.e('success')" >> .github/resources/init-integration.lua
          nvim -u .github/resources/init-integration.lua -c 'set noswapfile' +wq
          if [ ! -f success ]; then
            echo "Integration test failed!"
            exit 1
          fi
