---
name: Review Checklist

on:
  pull_request_target:
    types: [opened, review_requested]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  review-checklist:
    name: Review Checklist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body
            if (body && (body.startsWith(":robot: I have created a release *beep* *boop*") || body.startsWith("Automated changes"))) {
               return; // PR created by bot
            }

            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              if (issue.number === context.issue.number) {
                continue
              }

              if (issue.pull_request) {
                return // Creator is already a contributor.
              }
            }

            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // if comment already exists, then just return
            if (comments.find(comment => comment.body.includes("### Review Checklist"))) { return; }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Review Checklist

            Does this PR follow the [Contribution Guidelines](https://github.com/nvim-neorocks/rocks.nvim/blob/master/CONTRIBUTING.md)? Following is a _partial_ checklist:

            Proper [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) scoping:

            - For example, fix(installer): some installer bugfix

            - [ ] Pull request title has the appropriate conventional commit prefix.

            If applicable:

            - [ ] Tested
              - [ ] Tests have been added.
              - [ ] Tested manually (steps in PR description).
            - [ ] Updated documentation.
            `,
            })
